### ISSUE TITLE
MAAP: Generate multiple addresses

### ISSUE THREAD

**Issue by davidcemin** [AVnu/OpenAvnu#190]
It would be good to be able to generate more than one address with maap daemon. Currently, It generates a single multicast mac addr (function generate_address at common/maap_protocol.c). This is only useful if we have just one talker, but we would require more addresses for devices with more than one talker.

**Comment by andrew-elder** [comment]
@bdthomsen - can we close this?

**Comment by bdthomsen** [comment]
This issue is addressed by the recent MAAP daemon updates.
