### ISSUE TITLE
MAAP: Notify when address is ready to use

### ISSUE THREAD

**Issue by davidcemin** [AVnu/OpenAvnu#191]
Currently maap creates a shared memory and put the generated address there. Other processes that use these addresses need to monitor the shared memory in order to know when the address is ready to be used. As an enhancement, we could have a notification method when the addresses are ready to use, which would avoid other processes to poll the shared memory waiting for a change.

**Comment by andrew-elder** [comment]
@bdthomsen - can we close this?

**Comment by bdthomsen** [comment]
This issue is addressed by the recent MAAP daemon updates.  Communication with the MAAP daemon using a 2-way socket is supported.
