### ISSUE TITLE
How to calculate credit based shaper values

### ISSUE THREAD

**Issue by keyurparekh1** [Avnu/OpenAvnu#39]
Hello,

I am currently trying to understand credit based shaper algorithm. but I don't understand how to calculate hi credit. low credit , send slop and ideal slop values? 

Can anybody provide some equation to calculate these values?

**Comment by rohan-lt** [comment]
hi @keyurparekh1 
did u get solution for above problem?
 i am also working on the CBS algorithm

**Comment by rohan-lt** [comment]
hi @keyurparekh1 did u find the solution for ur problem 
if u provide some help on this it will be very helpful

**Comment by amiguptaa2000** [comment]
Hi @keyurparekh1 , @rohan-lt ,
Please let me know how you solved the above problem.
i am also working on the CBS algorithm

**Comment by anushaupadya7** [comment]
CBS on Omnet ++ ! Any idea? I am stuck with it
