### ISSUE TITLE
jackd_listener underruns

### ISSUE THREAD

**Issue by jsonder** [Avnu/OpenAvnu#46]
I finally figured out how to use JACK and have the jackd_talker/listener working.  I am using the built-in sound cards on two machines running Ubuntu 12.04 LTS.  After about 30 seconds, the listener starts reporting underruns and (obviously) I hear these artifacts.  I am using rtprio at 86 (both ends) and RT scheduling in the talker at 89.  Buffers are at 2048.  Made no difference.  I assume the underruns are due to my clock domains drifting with respect to one another.  A few questions:
1) What does Intel recommend for media clock recovery?
2) In the short run, should I use external USB sound cards with a synchronous word clock?  Do you think this would eliminate the underruns?
3) Long term, if there was some type of pilot stream that provides media clock data, how would this data control a external USB sound card?
4) Some said the IGB i210 card has a clock output on it. What is this for?

I have developed several readme files for both simple listener/talker and jackd versions.  I also have created scripts to set everything up (all daemons, applications, etc.).  I can submit these if anyone cares.  Most of this would fall under "Documentation".  I also fixed the jackd_talker so it would connect the ports automatically (internal sound card to the jackd_talker) without requiring this to be done manually.  I presume Adrian did not do this because of the clock drift issues and he was using some external USB sound card.

**Comment by SumeetPJain** [comment]
@jsonder 
Can you update me on how you made this jack applications work ?

Thanks
Sumeet

**Comment by jsonder** [comment]
Sumseet,

Not sure you will like Jackd listener and talker example.  The two clocks drift with time and the jackd listener eventually produces a underrun or overrun in about 30-45 seconds depending on the clock drift of the two media clocks in each PC.  Better to put a talker and listener on the same PC (for demonstration purposes).  Without media clock recovery or some type of sample rate conversion to match the listener to the talker, it simply won’t work long term – only a few minutes maximum.

Jeff
