### ISSUE TITLE
OPEN-AVB which is used to open the board? 

### ISSUE THREAD

**Issue by jluhuangj** [AVnu/OpenAvnu#520]
Is this one?
Http://www.digikey.com/product-search/en?KeyWords=XK-AVB-LC-SYS

Or just need to exist in the two end Inter i210 the NIC can run the code?

Is the code running on a PC? Or running on the development board?

If I want it to run on an open board, what needs to be done?

Sorry, my problem is a little bit more and it's very confusing.
Thank you for spending time to watch, and my English is not good I am sorry.

**Comment by andrew-elder** [comment]
I think 2 i210s running in 2 separate Linux PCs is a good place to start.

**Comment by jluhuangj** [comment]
http://www.intel.eu/content/www/eu/en/embedded/products/networking/ethernet-controller-i210-i211-family-overview.html

@andrew-elder Is this series？

**Comment by andrew-elder** [comment]
Yes. PCIe cards with an i210 are readily available.
