### ISSUE TITLE
What is the effect of the code running end?

### ISSUE THREAD

**Issue by jluhuangj** [AVnu/OpenAvnu#521]
I was new to AVB students, see the code should be the first implementation of travis.sh, but the implementation of this. Sh after the effect of what is it? I have not seen these descriptions in the documentation.

Thank you for spending time to watch, and my English is not good I am sorry.

**Comment by andrew-elder** [comment]
Have you read this readme file https://github.com/AVnu/Open-AVB/tree/master/lib/avtp_pipeline ?

**Comment by pinealservo** [comment]
Closing due to lack of response from original opener.
