### ISSUE TITLE
CMake-file for daemon_cl?

### ISSUE THREAD

**Issue by yescope** [AVnu/OpenAvnu#553]
Hello,

I am trying to build the daemon_cl application for Windows using Visual Studio 2015. Is there any CMakeLists.txt available for that application? 
The one that is present in OpenAvnu-master\daemons\gptp\ only sets the project for the named_pipe_test but not for teh daemon_cl.

Cheers,

Martin

**Comment by pinealservo** [comment]
It sets the project at the top of that file to 'gptp' and has an `add_executable` directive for the `gptp` executable target. That's the executable that's named `daemon_cl` in the Linux build. The `named_pipe_test` just supplies an additional target.

The file `daemons\gptp\CMakeLists.txt` really is the one you're looking for.
