### ISSUE TITLE
Delete old branches

### ISSUE THREAD

**Issue by andrew-elder** [AVnu/OpenAvnu#576]
I think we are safe to delete the following "feature" branches:
feature-avtp-pipeline
feature-gptp-avnu-automotive-profile
anyone object?

There are other branches that may be candidates for deletion, but I'm not 100% sure of status, so I'll leave them.

**Comment by kencarlino** [comment]
No objection from me. (Explicitly stated since these branches were originally requested by me).

**Comment by andrew-elder** [comment]
I just deleted those two branches on GitHub.
