### ISSUE TITLE
BroadR-Reach PHY scrambler and descrambler synchronization issue

### ISSUE THREAD

**Issue by amiguptaa2000** [AVnu/OpenAvnu#599]
Hi,
I am implementing PCS of BroadR-Reach PHY, 
In the specification the synchronization of scrambler and descrambler is not given properly.

I understand that it is additive type of scrambler and this type of scrambler
requires sync word, but what is the value of sync word is not defined.
Can you please help me on the synchronization of scrambler/descrambler.

Thanks in advance.
--Amit

**Comment by pinealservo** [comment]
I'm sorry, but questions about the BroadR-Reach PHY are currently outside the scope of this Github repository. I don't think anyone monitoring the issue tracker here happens to know the answer either. I have used BroadR-Reach PHYs before, but never had to do anything at the level you're asking about. This sounds like a question your part supplier would be best-equipped to answer for you.
