### ISSUE TITLE
Tx Timestamp (gPTP)

### ISSUE THREAD

**Issue by riteshjaiswal2016** [AVnu/OpenAvnu#617]
How can we print the timestamps which are transmitted using FollowUp messages (gPTP)?

**Comment by andrew-elder** [comment]
You mean like this https://github.com/AVnu/OpenAvnu/blob/master/daemons/gptp/common/ptp_message.cpp#L1710
?

**Comment by christopher-s-hall** [comment]
[look here](https://github.com/AVnu/OpenAvnu/blob/master/daemons/gptp/common/ptp_message.cpp#L906)

and change the output to VERBOSE

**Comment by riteshjaiswal2016** [comment]
Thank you for guiding me. Now, I am able to get the timestamps values in FollowUp(Synch) and FollowUp(PDelay_Resp). 
One more thing, Can you please guide me on how can I print the time when a packet from simple_talker just get transmitted from the NIC? Also, gPTP time is the time which will get set on master and slaves after synchronization between them? Can you please clear the meanings of Device time, System time and gPTP time?
