### ISSUE TITLE
Hardware Timestamping

### ISSUE THREAD

**Issue by riteshjaiswal2016** [AVnu/OpenAvnu#633]
Hello,
My configuration is-
PC2<-->AVB Switch<-->PC1

I synchronized both the PCs with AVB Switch and now I am using simple_talker at PC2 and simple_rx at PC1. I want to receive the precise time when an AVB packet (which is sent using simple_talker) is get received at PC2 at NIC. So,

Question:
(1). If we want to receive the hardware timestamp in the receive buffer on reception of a packet then according to i210 Datasheet (7.1.6)-
The Timestamp in Buffer is enabled by the following settings:
• The 1588 logic must not be disabled by the TSAUXC.Disable systime flag (it should be cleared)
• The RXPBSIZE.cfg_ts_en flag should be set, allocating the extra 16 bytes in the packet buffer for
the received packets
• Specific setting of the relevant receive queues by the SRRCTL[n] registers
— The Timestamp flag should be set, instructing the hardware to post the timestamp in the
packet buffer
— If the DESCTYPE is set to any of the header split modes then the BSIZEHEADER field should be
set to a larger header buffer than 128 bytes  

By using these steps, can I get the hardware timestamp value before the MAC header of AVB packet on reception of those AVB packets using simple_rx at PC1 (Transmitted from simple_talker at PC2)? Do I need to deal with any rx filters as well?

(2). Could you please explain me the field TSYNCRXCTL.Type
For your reference from datasheet i210-
Type of Packets to Timestamp.
000b = Timestamp L2 (V2) packets with MessageType as defined by MSGT field in the
TSYNCRXCFG register as well as DELAY_REQ and DELAY_RESP packets.
001b = Timestamp L4 (V1) packets with Control as defined by CTRLT field in the
TSYNCRXCFG register.
010b = Timestamp V2 (L2 and L4) packets with MessageType as defined by MSGT
field in the TSYNCRXCFG register as well as DELAY_REQ and DELAY_RESP packets.
100b = timestamp all packets.
101b = Timestamp all V2 packets which have a MessageType bit 3 zero, which means
timestamp all event packets.
011b, 110b and 111b = Reserved

Here what does "100b" Mean-
- all PTP V1, V2 Event Messages (Excluding other packets like AVB packets transmitted from simple_talker)  or
- each and every packet which come at NIC (Including all PTP V1, V2 and all AVB packets transmitted from simple_talker). ??
I am confused here because TSYNCRXCTL is for Time Sync purposes.

Thanks in advance!

**Comment by pinealservo** [comment]
It appears to really mean "all packets", not just all PTP packets. Since all packets meet the criteria set by 100b, you shouldn't need to set any filters. This is just based on my reading of the datasheet, though.

Just because the capability was added for time sync purposes and is managed in the same set of registers doesn't mean it's not useful for other things.
