### ISSUE TITLE
[gPTP Daemon] Accessing gPTP data from shm/ptp

### ISSUE THREAD

**Issue by vitorroriz** [AVnu/OpenAvnu#636]
Good day all.

I have now two imx7 Dual Sabre boards connected and running the gPTP daemon. From the stdout I can see that both arrive in the "asCapable" state. I am running then a simple program to read the /shm/ptp file and print all its variable values. However those values are alway 0. Also, when I tried to directly execute a hexdump from the terminal against the ptp file, it seems that its content never changes. Any hints?

Salutes! :)

**Comment by pinealservo** [comment]
I think you've figured out what was happening here--the default intervals were set incorrectly due to a bug and gPTP was not really working at all as a result. I'm going to close this issue since it overlaps with the other one you have open.
