### ISSUE TITLE
Reporting back feature of i210

### ISSUE THREAD

**Issue by riteshjaiswal2016** [AVnu/OpenAvnu#643]
Hello,
My configuration is-
PC2<-->AVB Switch<-->PC1

I synchronized both the PCs with AVB Switch and now I am using simple_talker at PC2 and simple_rx at PC1. I want to receive the precise time when an AVB packet (which is sent using simple_talker) is get sent by PC2.
Could you please guide me on how can I implement the method mentioned in i210 datasheet in 1.7.2.1 "Reporting back of the timestamp in the transmit descriptor"?

Thanks in advance!

**Comment by andrew-elder** [comment]
The folks that volunteer their time replying to comments on this forum don't have the time to keep providing advice on how to measure EXACTLY when a AVTP packet is transmitted from an i210. It's not an interesting problem to solve. If you wish to measure it, but a network tap between PC2 and the switch and record all the packets. You can compare packet timestamps with gPTP SYNC packets in the recorded packet stream to work out exactly when the AVTP packet was put on the wire.
