### ISSUE TITLE
Compilation of Open-gPTP for ARM

### ISSUE THREAD

**Issue by SUBBU3881** [AVnu/OpenAvnu#703]
Hi,
     Can anyone suggest that how to cross compile the open-AVB gPTP for ARM architecture.? How can I change the Makefile for cross compilation.? I had a PC loaded by Ubuntu 12.04 and installed the ARM cross compiler.

Please, respond as soon as possible.

Thanks and Regads,
Narreddi Siva Prakash Reddy

**Comment by pinealservo** [comment]
Hi,

I sympathize with your problem, but I'm afraid we don't have the bandwidth here to give this level of support. The gPTP daemon will cross-compile and work on ARM, but I can't teach you how to set up cross-compilation for your system. Fortunately, there are a lot of resources out there to learn how to cross-compile, and you should be able to find some with a web search.

Once you can successfully cross-compile other things, if you have specific problems cross-compiling gPTP, please open another issue and we can probably help with that. Good luck!
