### ISSUE TITLE
GPTP Daemon Windows 10 Testing?

### ISSUE THREAD

**Issue by gsilva2016** [AVnu/OpenAvnu#730]
Has GPTP Daemon been tested on Windows 10 with Intel 82579LM network controller? I have tried testing this with eXtreme network switch Summit x440-24t with no luck (ReturnSyncStatus always returns 0). On Win7 I do not have any issues, but the Win7 OS does have e1c62x64.sys driver installed.

**Comment by christopher-s-hall** [comment]
Which driver are you using on Win10? The "inbox" driver won't work.

**Comment by gabe2004** [comment]
I am testing with what Win10 installed: Provider: Intel, Driver Date: 7/25/2016, Version: 12.15.31.4, Files: e1c65x64.sys,e1c65x64.din, e1cmsg.dll, NicCo4.dll, NicInstC.dll.  I also already enabled TimeSync DWORD = 1 in the registry so I am thinking this driver may not check this registry key.

**Comment by christopher-s-hall** [comment]
That sounds OK, but maybe update the driver to a newer version? 22.6 should be a recent version.

https://downloadcenter.intel.com/download/27177/Intel-Network-Adapter-Driver-for-Windows-10

I don't know of any reason older HW shouldn't work with Win10. Unfortunately, I only have newer HW for my own testing.

**Comment by gabe2004** [comment]
Thanks we can close this issue. I was using the latest driver from Intel already.  However, I tested using newer hardware I219-LM and KabyLake i5 instead and worked without issues.

**Comment by andrew-elder** [comment]
Great!

**Comment by shirArg** [comment]
I am facing the same problem (I think) using I219-LM, and the latest driver from Intel site. 
I added TimeSync to the registry, but some how it seems that the driver is not reading this value- 

INFO     : GPTP [13:43:34:438] Starting IPC listener thread succeeded
Opening: rpcap://\Device\NPF_{33F88F37-D54C-4965-B2FA-EA134B078A74}
ERROR    : GPTP [13:43:34:561] Unable to determine clock rate for interface Intel(R) Ethernet Connection (2) I219-LM
ERROR    : GPTP [13:43:34:565] Failed to initialize hardware timestamper, falling back to software timestamping
STATUS   : GPTP [13:43:34:566] Starting PDelay
Error is: 6
Error is: 6
Error is: 6
Error is: 6
Error is: 6
Error is: 6
ERROR    : GPTP [13:43:34:701] Error (TX) timestamping PDelay request (Retrying-0), error=-1
Error is: 6
ERROR    : GPTP [13:43:34:704] Error (TX) timestamping PDelay request, error=-1
Error is: 6


Any idea how to solve this? 

Thanks

**Comment by christopher-s-hall** [comment]
I'm working on getting this working on I219-LM. I *think* you can modify the code to use the same clock rate as I219. I'm working to verify, but in the meantime you can try modifying the code to use the same clock rate as I219.

**Comment by StefanS52u1** [comment]
I'm facing the same issue. Has the problem be solved so far. Is the gPTP successfully running with the i219-LM?. If yes which modifications are required?

**Comment by Ossama-MOUSTAFA** [comment]
Hi. Me too I am trying to use this with a i219-LM. 

`/**
* @brief Maps network device type to device clock rate
*/
static DeviceClockRateMapping DeviceClockRateMap[] =
{
	{ 1000000000, I217_DESC }, 
	{ 1008000000, I219_V_DESC }, 
	{ 1000000000, I210_DESC }, 
	{ 1008000000, I219_LM_DESC	}, // This one. 
	{ 0, NULL },
};`

But I just get the error "ERROR_GEN_FAILURE", when I try to get the TX hardware timestamp. (on windows)
( WindowsEtherTimestamper::HWTimestamper_txtimestamp with OID_INTEL_GET_TXSTAMP )

Does anyone have any idea about this, please ?
