### ISSUE TITLE
New kernel issues: updating igb-avb?

### ISSUE THREAD

**Issue by ethan-stewart-iol** [AVnu/OpenAvnu#753]
igb-avb has issues building against newer kernels. Rather than spot check them, how easy is it to sync the changes from the igb in the kernel? (which is now igb-5.4.0).

With the kernel I'm building against (4.13.0), I think there's only three issues.

**Comment by pinealservo** [comment]
There are some Intel developers that periodically supply updates to keep igb-avb building with newer kernels. I'm not sure how valuable it would be to port the libigb interface to the latest upstream igb driver; it's not acceptable to the upstream kernel, and there is work in progress to provide replacements to its functionality (configuring the traffic shaping and launch time descriptors) upstream without requiring full userspace control of the queue.

Anyway, we just merged some changes to our next brach, so you might check to see if igb-avb builds for you now.

**Comment by ghindman** [comment]
Yes, qav/fqtss support for mainline IGB is in kernel 4.15, and updated v3 RFC to support time-based transmission/launchtime is being prepared now for the netdev mailing list.  v2 is here: https://patchwork.ozlabs.org/cover/862639/

**Comment by andrew-elder** [comment]
Great!

**Comment by jfornal** [comment]
Currently the igb_avb driver already supports newer kernel versions (4.16) - compilation errors have been already resolved.

**Comment by ethan-stewart-iol** [comment]
Short of actually testing anything, it builds as expected.
Marking closed.
