### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by varun-v-deshpande** [AVnu/OpenAvnu#772]
Hello, 

I am trying to compile AVB but I am getting this error :
[Error_AVB.txt](https://github.com/AVnu/OpenAvnu/files/1847487/Error_AVB.txt)

The details of my system are : 
` Linux ubuntu-5151 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux `

How can I solve it ? Is this kernel supported by AVB ?

**Comment by andrew-elder** [comment]
What branch are you compiling?

**Comment by varun-v-deshpande** [comment]
Master Branch.

सोम, २६, मार्च २०१८, २:०० म.उ. ला andrew-elder ने <notifications@github.com>
लिहीला:

**Comment by andrew-elder** [comment]
Try open-avb-next branch

**Comment by varun-v-deshpande** [comment]
Yes, it works, Thank you
(Sorry to inform you late)
