### ISSUE TITLE
Which one is Better  to run Open Avnu Master or Open Avnu Next 

### ISSUE THREAD

**Issue by Ravi-Teja-konda** [AVnu/OpenAvnu#788]
Hello All,

which one is better to use "Open Avnu -Master" or " Open Avnu _next" ?

**Comment by andrew-elder** [comment]
Typically "master" would be the place to start. You can see the diff between master and open-avnu-next here
https://github.com/AVnu/OpenAvnu/compare/open-avb-next

We will plan to merge the "next" branch in to "master" soon.

**Comment by Ravi-Teja-konda** [comment]
Thank you for the reply, it helped me a lot.
