### ISSUE TITLE
Qbv implementation?

### ISSUE THREAD

**Issue by kalkhour** [AVnu/OpenAvnu#801]
Hi,
Is there any implementation that handles the traffic scheduling in this repository? According to my little knowledge in TSN, I thought traffic scheduling is a basic requirement and I was expecting to find an implementation of IEEE 802.1Qbv in this project but I couldn't. Am I missing something here?

(if this is not the right place to ask this question please guide me...)

Thanks.

**Comment by ethan-stewart-iol** [comment]
See #686, I'm not sure if anything has changed since then though.
