### ISSUE TITLE
where is gptp maintained?

### ISSUE THREAD

**Issue by sarh2o** [AVnu/OpenAvnu#862]
I found that gPTP has its own repo:https://github.com/AVnu/gptp. So I am confused. Which one is the latest and maintained one?

Thanks!

**Comment by andrew-elder** [comment]
The one here https://github.com/AVnu/gptp is the one to use. It was broken out a while ago. However, keep in mind that this test branch here https://github.com/AVnu/OpenAvnu/commits/feature-aptp-experimental was never moved to the standalone gptp repository.

**Comment by sarh2o** [comment]
Hi @andrew-elder ,
got it! Great thanks for your answer!:)
