### ISSUE TITLE
Organization name change

### ISSUE THREAD

**Issue by andrew-elder** [Avnu/OpenAvnu#893]
I have had a request to change the top level name of this repo from "AVnu" to "Avnu". ie, correct the capitalization. The name change will probably break quite a few things. Any comments?

**Comment by aguedes** [comment]
According to https://github.community/t5/How-to-use-Git-and-GitHub/Changing-username-case/td-p/6714, it seems the username is not case sensitive so it might not break things. But I'd recommend to verify this first. Break things is not good :)

**Comment by christopher-s-hall** [comment]
The URL seems case insensitive

git clone https://github.com/avNU/OpenAvnu.git
git clone https://github.com/Avnu/OpenAvnu.git

Both work. Not what other considerations there might be.

**Comment by andrew-elder** [comment]
Thanks for testing @christopher-s-hall - that was a good idea! I'll make the change then.

**Comment by andrew-elder** [comment]
Name has changed. I'll keep this issue open in case there are some issues that I am unaware of at this time.

**Comment by andrew-elder** [comment]
It's been almost 3 weeks. No side effects reported here at least. Closing this issue.
