### ISSUE TITLE
Running Open-AVB gPTP daemon on a gateway device

### ISSUE THREAD

**Issue by Debarun-RC** [Avnu/OpenAvnu#922]
Hi All,

  I am studying https://github.com/ni/Open-AVB/tree/master/daemons/gptp code. I intend to run it on Timeaware endpoints as well as on gateway devices. 
  Does the gPTP daemon support gateway devices like bridges and switches or is it only meant for endpoints?

**Comment by PawelModrzejewski** [comment]
gptp was moved to dedicated repository/project, check [AVnu/gptp](https://github.com/Avnu/gptp) but as far as I know it's dedicated to endpoints only.

**Comment by Debarun-RC** [comment]
Hi Pawel,

  Thank you for your reply. It is really helpful!

Best Regards,
Debarun
