### ISSUE TITLE
avb-igb build failing, does avb-igb build supports on latest ubuntu 22.04 and kernal 6.5.0-15?

### ISSUE THREAD

**Issue by varahalu10406** [Avnu/OpenAvnu#933]
igb_main.c:239:27: error: initialization of ‘vm_fault_t (*)(struct vm_fault *)’ {aka ‘unsigned int (*)(struct vm_fault *)’} from incompatible pointer type ‘int (*)(struct vm_fault *)’ [-Werror=incompatible-pointer-types]
  239 |                 .fault  = igb_vm_fault

**Comment by MarcinMiklas** [comment]
It looks like you didn't have the last version of igb_avb subrepo.

Go to  lib/igb_avb subfolder and checkout latest master branch like this:

  git checkout master
  git pull

Submodules commits are not automatically updated in master OpenAvnu repo.

**Comment by varahalu10406** [comment]
Thanks; it fixed the compilation issue.
But i am getting one more error
root@user:OpenAvnu/lib/igb_avb/igb_avb/kmod# ARCH=I210 make
make -C /lib/modules/6.5.0-15-generic/build M=/home/user/OpenAvnu/lib/igb_avb/igb_avb/kmod modules
make[1]: Entering directory '/usr/src/linux-headers-6.5.0-15-generic'
/usr/src/linux-headers-6.5.0-15-generic/Makefile:779: arch/I210/Makefile: No such file or directory
make[2]: *** No rule to make target 'arch/I210/Makefile'.  Stop.
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.5.0-15-generic'
make: *** [Makefile:267: default] Error 2

**Comment by varahalu10406** [comment]
Thanks , it's worked.

**Comment by MarcinMiklas** [comment]
Please check dmesg output for more details. I don't have that kernel on any of my machines to check myself.

**Comment by MarcinMiklas** [comment]
Great, so I am closing the issue.
